apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - ping
      - "10.10.18.123"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: /data
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /data
  restartPolicy: Always
